workflows:
  ios-workflow:
    name: Taxi Paradis iOS
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/ios
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
    artifacts:
      - build/ios/ipa/*.ipa
